// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/google/uuid"
)

type User struct {
	ID       uuid.UUID
	Username string
	Age      int32
}
