// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package storage

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, age)
VALUES (
        $1::text, $2::int
)
RETURNING id, username, age
`

type CreateUserParams struct {
	Username string
	Age      int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Age)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Age)
	return i, err
}
